---

- name: Add apache2.4 Repository
  apt_repository: repo='ppa:ondrej/apache2' state=present
  sudo: yes
  register: apache24repoAdded

- name: Install Apache
  sudo: yes
  apt: pkg={{item}} state=latest update_cache=true
  with_items:
     - python-software-properties
     - apache2
  register: apacheInstalled
  notify:
    - Reload Apache2

- name: enabled mod_rewrite
  sudo: yes
  apache2_module: state=present name=rewrite
  when: apacheInstalled|success
  notify:
      - Reload Apache2

# - name: write our apache2.conf
#   sudo: yes
#   template: src=apache2.conf.j2 dest=/etc/apache2/apache2.conf
#   notify: Reload Apache2


- name: write our /etc/apache2/sites-available/default
  sudo: yes
  template: src=default-site.j2 dest=/etc/apache2/sites-available/000-default.conf
  notify: Reload Apache2


- debug: msg="{{apache_vhosts}}"

- name: write each site conf
  sudo: yes
  template: src=php-site.j2 dest=/etc/apache2/sites-available/{{item.servername}}.conf
  with_items: "{{apache_vhosts}}"
  notify: Reload Apache2


- name: a2ensite all sites
  sudo: yes
  command: a2ensite {{ item.servername }}.conf
  args:
    creates: /etc/apache2/sites-enabled/{{ item.servername }}.conf
  with_items: "{{apache_vhosts}}"
  notify:
    - Reload Apache2