CREATE TABLE `actions` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `creation_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_modified` datetime DEFAULT NULL,
  `action` smallint(5) unsigned NOT NULL,
  `executor_type` enum('user','contact','account','application','registration','cron') NOT NULL,
  `executor_id` mediumint(8) unsigned NOT NULL,
  `contact_id` mediumint(8) unsigned DEFAULT NULL,
  `account_id` mediumint(8) unsigned DEFAULT NULL,
  `subscriber_id` mediumint(8) unsigned DEFAULT NULL,
  `NDC_SN` char(9) DEFAULT NULL,
  `sim_iccid` char(20) DEFAULT NULL COMMENT '89972010411040356231',
  `order_id` mediumint(8) unsigned DEFAULT NULL,
  `order_item_id` mediumint(8) unsigned DEFAULT NULL,
  `invoice_id` bigint(10) unsigned DEFAULT NULL,
  `raw_data` text,
  `description` text,
  `remark` text,
  `success` tinyint(1) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `account_id` (`account_id`),
  KEY `executor_id` (`executor_id`),
  KEY `remark` (`remark`(255)),
  KEY `invoice_id` (`invoice_id`),
  KEY `success` (`success`),
  KEY `sim_iccid` (`sim_iccid`),
  KEY `IX_creation_date_action` (`creation_date`,`action`),
  KEY `NDC_SN` (`NDC_SN`,`action`),
  KEY `IX_action_creation_date_NDC_SN_subscriber_id` (`action`,`creation_date`,`NDC_SN`,`subscriber_id`),
  KEY `IX_subscriber_id_action_creation_date` (`subscriber_id`,`action`,`creation_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8