---

- name: Debian | Add keys authenticity
  sudo: yes
  apt_key: url={{ url_apt_key }}0x7F0CEB10

- name: Debian | Add source sources
  sudo: yes
  apt_repository: repo='{{ mongodb_repository }}' update_cache=yes

- name: Debian | Install Packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items: mongodb_packages
