---

- name: download node stuff
  become: true
  get_url: url=https://deb.nodesource.com/setup_6.x dest=~/nodestuff mode=0440

- name: run nodestuff
  become: true
  shell: bash nodestuff
  args:
    chdir: ~/

- name: install node
  become: true
  apt: 
    name: nodejs
    state: latest