---

- name: Start Supervisor
  sudo: yes
  service: name=supervisor state=started enabled=yes

- name: Restart Supervisor
  sudo: yes
  service: name=supervisor state=restarted enabled=yes

- name: start supervised confs
  supervisorctl: name={{whatever.results[0].item.name}} state=started
