---

- name: Add Nginx Repository
  apt_repository: repo='ppa:ondrej/php5' state=present
  sudo: yes
  register: nginxrepoAdded

- name: Install nginx
  sudo: yes
  apt: pkg={{item}} state=latest update_cache=true
  with_items:
     - python-software-properties
     - nginx-common
     - nginx
  when: nginxrepoAdded|success
  notify:
    - Reload Nginx

- name: write our nginx.conf
  sudo: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: Reload Nginx

- name: write our /etc/nginx/sites-available/default
  sudo: yes
  template: src=default-site.j2 dest=/etc/nginx/sites-available/default
  notify: Reload Nginx

- name: write each site conf
  sudo: yes
  template: src={{item.confType}}-site.j2 dest=/etc/nginx/sites-available/{{item.servername}}.conf
  with_items: "{{nginx_vhosts}}"
  notify: Reload Nginx

- name: To create softlink action
  sudo: yes
  file: src=/etc/nginx/sites-available/{{item.servername}}.conf dest=/etc/nginx/sites-enabled/{{item.servername}}.conf state=link
  with_items: "{{nginx_vhosts}}"
  notify: Reload Nginx








- name: ensure php5-fpm cgi.fix_pathinfo=0
  lineinfile: dest=/etc/php5/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
  notify:
    - Restart php5-fpm
    - restart nginx


- name: enable php5 mcrypt module
  shell: php5enmod mcrypt
  args:
    creates: /etc/php5/cli/conf.d/20-mcrypt.ini