---

- name: Add Nginx Repository
  apt_repository: repo='ppa:ondrej/php5' state=present
  sudo: yes
  register: nginxrepoAdded

- name: Install nginx
  sudo: yes
  apt: pkg={{item}} state=latest update_cache=true
  with_items:
     - python-software-properties
     - nginx-common
     - nginx
     - php5-fpm
     - php5
     - php5-cli
     - php5-curl
     - php5-gd
     - php5-mcrypt
  when: nginxrepoAdded|success
  notify:
    - Reload Nginx

- name: write our nginx.conf
  sudo: yes
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: Reload Nginx

- name: write our /etc/nginx/sites-available/default
  sudo: yes
  template: src=default-site.j2 dest=/etc/nginx/sites-available/default
  notify: Reload Nginx

- name: write each site conf
  sudo: yes
  template: src=php-site.j2 dest=/etc/nginx/sites-available/{{item.servername}}.conf
  with_items: "{{nginx_vhosts}}"
  notify: Reload Nginx