---

- name: Install nginx
  become: true
  apt: pkg={{item}} state=latest update_cache=true
  with_items:
     - python-software-properties
     - nginx-common
     - nginx
  notify:
    - Reload Nginx

- name: write our nginx.conf
  become: true
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: Reload Nginx

- name: write our /etc/nginx/sites-available/default
  become: true
  template: src=default-site.j2 dest=/etc/nginx/sites-available/default
  notify: Reload Nginx

- name: write each site conf
  become: true
  template: src={{item.confType}}-site.j2 dest=/etc/nginx/sites-available/{{item.servername}}.conf
  with_items: "{{nginx_vhosts}}"
  notify: Reload Nginx

- name: To create softlink action
  become: true
  file: src=/etc/nginx/sites-available/{{item.servername}}.conf dest=/etc/nginx/sites-enabled/{{item.servername}}.conf state=link
  with_items: "{{nginx_vhosts}}"
  notify: Reload Nginx