---

- name: check out a git repository
  local_action: git
    repo={{item.git}}
    dest={{item.localPath}}
  with_items: repos  

- name: composer install deps
  local_action: composer command=install working_dir={{item.localPath}}
  with_items: repos  

- name: optimize code
  local_action: command php {{item.localPath}}/artisan optimize
  with_items: repos  