---

# file: webservers.yml
- hosts: web2
  gather_facts: no

  vars:
    apache_vhosts:
      - {servername: "babelfish.local", documentroot: "/web/babelfish/public/"}
      - {servername: "cellular.local", documentroot: "/web/cellular/"}
    mysql_dbs:
      - name: babelfish
      - name: gtcrm

  roles:
    roles:
        - {role: golan, apache_vhosts: [
              {servername: "babelfish.local", documentroot: "/web/babelfish/public/"},
              {servername: "cellular.local", documentroot: "/web/cellular/"}
              ],
          }