---

# file: webservers.yml
- hosts: web
  gather_facts: no

  vars:
    supervisorConfs: []
#      - {
#          name: "nameOfTask",
#          autorestart: true,
#          user: "www-data",
#          autostart: true,
#          command: "bash /home/vagrant/boom.sh",
#          stdout_logfile: "/tmp/supp.log"
#        }

  roles:
    - rabbitmq
    - supervisor
