---

# file: webservers.yml
- hosts: web

  vars:
    apache_vhosts:
      - {servername: "babelfish.local", documentroot: "/web/babelfish/public/"}
    mysql_dbs:
      - name: babelfish

  roles:
    - mysql
    - apache #only this install all needed for apache-php server
    #- nginx #only this install all needed for nginx-php server
    #- php56
    #- nodejs
